version: '3.8'

services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: meal-planner-db
    environment:
      POSTGRES_DB: mealdb
      POSTGRES_USER: mealuser
      POSTGRES_PASSWORD: mealpass123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: meal-planner-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data: 